name: "Secrets Scan"
description: "Run detect-secrets and normalize results into unified report format"

inputs: {}

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Install detect-secrets
      shell: bash
      run: |
        python -m pip install --upgrade pip || true
        python -m pip install detect-secrets

    - name: Run detect-secrets
      shell: bash
      run: |
        mkdir -p raw normalized
        CONFIG_PATH="templates/detect-secrets.config"
        if [[ -f "$CONFIG_PATH" ]]; then
          detect-secrets scan --all-files --config "$CONFIG_PATH" > raw/detect-secrets.json || true
        else
          detect-secrets scan --all-files > raw/detect-secrets.json || true
        fi

        python3 tools/normalize_report.py \
          --input raw/detect-secrets.json \
          --output normalized/detect-secrets-normalized.json \
          --scanner detect-secrets


