name: "Pip Audit"
description: "Run pip-audit and normalize results into unified report format"

inputs: {}

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Install pip-audit
      shell: bash
      run: |
        python -m pip install --upgrade pip || true
        python -m pip install pip-audit

    - name: Run pip-audit
      shell: bash
      run: |
        mkdir -p raw normalized
        if [[ -f requirements.txt ]]; then
          pip-audit -r requirements.txt -f json -o raw/pip-audit.json || true
        else
          pip-audit -f json -o raw/pip-audit.json || true
        fi

        python3 tools/normalize_report.py \
          --input raw/pip-audit.json \
          --output normalized/pip-audit-normalized.json \
          --scanner pip-audit


